# =============================================================================
# This pipeline publishes Python packages. Manually triggered only.
# - Internal: publishes unsigned packages to the internal TeamsSDKPreviews feed.
# - Public: publishes signed packages to PyPI via ESRP (requires approval).
# =============================================================================

trigger: none

pr: none

parameters:
- name: publishType
  displayName: 'Publish Type'
  type: string
  default: 'Internal'
  values:
  - Internal
  - Public

variables:
  ExcludePackageFolders: 'devtools'  # Space-separated list of distribution name fragments to exclude (matched as microsoft_teams_<value>*)

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES-Teams-Windows-2022-DomoreexpGithub
      os: windows
    stages:
    - stage: build
      displayName: Build and Test
      jobs:
      - job: build_test
        pool:
          name: 1ES-Teams-Windows-2022-DomoreexpGithub
          os: windows
        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)/out'
          ob_git_fetchTags: true
          ob_sdl_binskim_break: true
          ob_git_fetchDepth: -1

        steps:
        - checkout: self
          displayName: 'Checkout'
          fetchDepth: 0

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.13'
          inputs:
            versionSpec: '3.13'

        - task: UseDotNet@2
          displayName: 'Use .NET SDK'
          inputs:
            packageType: 'sdk'
            version: '8.x'

        - task: PowerShell@2
          displayName: 'Install uv and nbgv'
          inputs:
            targetType: inline
            script: |
              # Install uv
              irm https://astral.sh/uv/install.ps1 | iex
              $env:Path = "$env:USERPROFILE\.local\bin;$env:Path"
              [System.Environment]::SetEnvironmentVariable('Path', "$env:USERPROFILE\.local\bin;$([System.Environment]::GetEnvironmentVariable('Path', 'User'))", 'User')
              Write-Host "##vso[task.prependpath]$env:USERPROFILE\.local\bin"
              uv --version

              # Install nbgv
              dotnet tool install -g nbgv
              Write-Host "##vso[task.prependpath]$env:USERPROFILE\.dotnet\tools"
              nbgv --version

        - powershell: |
            Write-Host "Getting version from nbgv..."
            $version = (nbgv get-version -v SemVer2).Trim()
            Write-Host "Version from nbgv: $version"

            # If version contains '-' it's a prerelease, use 'next' tag; otherwise 'latest'
            if ($version -match '-') {
              Write-Host "Prerelease version detected - using 'next' PyPI tag"
              Write-Host "##vso[task.setvariable variable=PyPITag]next"
            } else {
              Write-Host "Stable version detected - using 'latest' PyPI tag"
              Write-Host "##vso[task.setvariable variable=PyPITag]latest"
            }
          displayName: 'Get version from nbgv'

        - task: PowerShell@2
          displayName: 'Install dependencies'
          inputs:
            targetType: inline
            script: |
              $pythonPath = (Get-Command python).Source
              Write-Host "Using Python at: $pythonPath"
              python --version
              # Create venv
              uv venv --python $pythonPath
              # Conditionally use internal feed
              $publishType = '${{ parameters.publishType }}'
              if ($publishType -eq 'Internal') {
                $indexUrl = "https://build:$($env:SYSTEM_ACCESSTOKEN)@pkgs.dev.azure.com/DomoreexpGithub/Github_Pipelines/_packaging/TeamsSDKPreviews/pypi/simple/"
                Write-Host "Using authenticated Azure Artifacts feed"
                uv pip install --index-url $indexUrl -e packages/common -e packages/api -e packages/cards -e packages/apps -e packages/botbuilder -e packages/graph -e packages/ai -e packages/openai -e packages/mcpplugin -e packages/a2aprotocol -e packages/devtools
              } else {
                Write-Host "Using public PyPI"
                uv pip install -e packages/common -e packages/api -e packages/cards -e packages/apps -e packages/botbuilder -e packages/graph -e packages/ai -e packages/openai -e packages/mcpplugin -e packages/a2aprotocol -e packages/devtools
              }
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

        - task: PowerShell@2
          displayName: 'Run tests'
          inputs:
            targetType: inline
            script: |
              Write-Host "Running tests..."
              $publishType = '${{ parameters.publishType }}'
              if ($publishType -eq 'Internal') {
                $env:UV_INDEX_URL = "https://build:$($env:SYSTEM_ACCESSTOKEN)@pkgs.dev.azure.com/DomoreexpGithub/Github_Pipelines/_packaging/TeamsSDKPreviews/pypi/simple/"
              }
              uv pip install pytest pytest-asyncio
              .venv\Scripts\Activate.ps1
              pytest packages --junitxml=test-results.xml
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          continueOnError: false

        - task: PublishTestResults@2
          displayName: 'Publish Test Results'
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/test-results.xml'
            mergeTestResults: true

        - task: PowerShell@2
          displayName: 'Build packages'
          inputs:
            targetType: inline
            script: |
              $pythonPath = (Get-Command python).Source
              # Conditionally use internal feed for build dependencies (hatchling, etc.)
              $publishType = '${{ parameters.publishType }}'
              if ($publishType -eq 'Internal') {
                $indexUrl = "https://build:$($env:SYSTEM_ACCESSTOKEN)@pkgs.dev.azure.com/DomoreexpGithub/Github_Pipelines/_packaging/TeamsSDKPreviews/pypi/simple/"
                $env:PIP_INDEX_URL = $indexUrl
                $env:UV_INDEX_URL = $indexUrl
                Write-Host "Using authenticated Azure Artifacts feed for build"
              } else {
                Write-Host "Using public PyPI for build"
              }
              Write-Host "Building packages (version determined by nbgv)..."
              uv build --all-packages --python $pythonPath
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

        - powershell: |
            New-Item -ItemType Directory -Force -Path ./out
            $excludeFolders = "$(ExcludePackageFolders)" -split '\s+'
            $excludePatterns = $excludeFolders | Where-Object { $_ } | ForEach-Object { "microsoft_teams_$_*" }

            Get-ChildItem -Path dist -File | ForEach-Object {
              $fileName = $_.Name
              $shouldExclude = $false

              foreach ($pattern in $excludePatterns) {
                if ($fileName -like $pattern) {
                  Write-Host "Skipping $fileName (matches exclude pattern: $pattern)"
                  $shouldExclude = $true
                  break
                }
              }

              if (-not $shouldExclude) {
                Write-Host "Copying $fileName to out/"
                Copy-Item $_.FullName -Destination ./out/
              }
            }

            Write-Host "`nFiles to publish:"
            Get-ChildItem ./out
          displayName: 'Copy packages to output (excluding private packages)'

    # Publish to internal PyPI feed (Azure Artifacts)
    - ${{ if eq(parameters.publishType, 'Internal') }}:
      - stage: publish_internal
        displayName: 'Publish to Internal Feed'
        dependsOn: build
        jobs:
        - job: publish
          displayName: 'Publish to Internal Feed'
          pool:
            name: 1ES-Teams-Windows-2022-DomoreexpGithub
            os: windows
          variables:
            ob_outputDirectory: '$(Build.SourcesDirectory)/out'
            ob_git_fetchDepth: -1
          steps:
          - download: current
            artifact: build_test

          - task: PowerShell@2
            displayName: 'Install uv'
            inputs:
              targetType: inline
              script: |
                irm https://astral.sh/uv/install.ps1 | iex
                $env:Path = "$env:USERPROFILE\.local\bin;$env:Path"
                Write-Host "##vso[task.prependpath]$env:USERPROFILE\.local\bin"
                uv --version

          - task: PowerShell@2
            displayName: 'Publish packages to internal PyPI feed'
            inputs:
              targetType: inline
              script: |
                $feedUrl = "https://pkgs.dev.azure.com/DomoreexpGithub/Github_Pipelines/_packaging/TeamsSDKPreviews/pypi/upload/"
                Write-Host "Publishing packages to internal feed..."
                uv publish --publish-url $feedUrl --token $env:SYSTEM_ACCESSTOKEN $(Pipeline.Workspace)/build_test/*
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    # Publish to PyPI via ESRP
    - ${{ if eq(parameters.publishType, 'Public') }}:
      - stage: publish_pypi
        displayName: 'Publish to PyPI via ESRP'
        dependsOn: build
        jobs:
        - deployment: publish
          displayName: 'Publish to PyPI via ESRP'
          environment: 'teams-sdk-publish'
          pool:
            name: 1ES-Teams-Windows-2022-DomoreexpGithub
            os: windows
          variables:
            ob_outputDirectory: '$(Build.SourcesDirectory)/out'
            ob_git_fetchDepth: -1
          strategy:
            runOnce:
              deploy:
                steps:
                - download: current
                  artifact: build_test

                - task: EsrpRelease@10
                  displayName: 'Publish packages to PyPI via ESRP'
                  inputs:
                    connectedservicename: 'TeamsESRP-Release-PyPI'
                    usemanagedidentity: true
                    keyvaultname: 'esrp-teams'
                    signcertname: '82a83c86-86a3-4739-8da4-fc19d60794ed'
                    clientid: '82a83c86-86a3-4739-8da4-fc19d60794ed'
                    intent: 'packagedistribution'
                    contenttype: 'PyPI'
                    contentsource: 'Folder'
                    folderlocation: '$(Pipeline.Workspace)/build_test'
                    waitforreleasecompletion: true
                    serviceendpointurl: 'https://api.esrp.microsoft.com'
                    mainpublisher: 'ESRPRELPACMAN'
                    domaintenantid: '975f013f-7f24-47e8-a7d3-abc4752bf346'
                    productState: $(PyPITag)
