repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
    - id: pyright

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        exclude: generated_handlers.py
        name: "Insert license header in python source files"
        args: [--license-filepath=PAGE_HEADER.txt,
               '--comment-style=',
               --detect-license-in-X-top-lines=4]
        types: [python]