repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          [
            --config-file=mypy.ini,
            --ignore-missing-imports,
            --show-traceback,
            --disable-error-code=import-untyped,
            --disable-error-code=no-untyped-call,
          ]
        additional_dependencies: [
            "pydantic>=2.0",
            "pydantic-core>=2.16.3",
            "typing-extensions>=4.9.0",
          ] # Needed for pre-commit's isolated environment
        files: ^packages/(?!.*tests/).+\.py$
