repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        exclude: generated_handlers.py
        name: "Insert license header in python source files"
        args: [--license-filepath=PAGE_HEADER.txt,
               '--comment-style=',
               --detect-license-in-X-top-lines=4]
        types: [python]