[project]
name = "microsoft-teams-auth"
version = "0.1.0"
description = "A package to help with authenticating requests from Bot Framework"
authors = [{ name = "Microsoft", email = "teams@microsoft.com" }]
readme = "README.md"
requires-python = ">=3.12"
repository = "https://github.com/microsoft/teams.py"
keywords = ["microsoft", "teams", "ai", "bot", "agents"]
license = "MIT"

dependencies = [
    "cryptography>=3.4.0",
    "microsoft-teams-common",
    "pyjwt[crypto]>=2.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/microsoft"]

[tool.uv.sources]
microsoft-teams-common = { workspace = true }
