from typing import List, Literal, Optional, Union

from .message_entity import MessageEntity


class AIMessageEntity(MessageEntity):
    additional_type: Optional[List[Union[Literal["AIGeneratedContent"], str]]]
    "Indicate that the content was generated by AI."
