[project]
name = "microsoft-teams-a2aprotocol"
version = "2.0.0a1"
description = "plugin that enables your teams agent to be used as an a2a agent"
authors = [{ name = "Microsoft", email = "TeamsAISDKFeedback@microsoft.com" }]
readme = "README.md"
requires-python = ">=3.12"
repository = "https://github.com/microsoft/teams.py"
keywords = ["microsoft", "teams", "ai", "bot", "agents"]
license = "MIT"
dependencies = [
    "a2a-sdk[all]>=0.3.7",
    "microsoft-teams-common",
    "pytest>=8.4.1",
]

[tool.microsoft-teams.metadata]
external = true


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/microsoft"]

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.uv.sources]
microsoft-teams-common = { workspace = true }
