"""
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License.
"""

import asyncio
from os import getenv

from dotenv import find_dotenv, load_dotenv
from microsoft_teams.api import MessageActivity, MessageActivityInput
from microsoft_teams.apps import ActivityContext, App
from microsoft_teams.devtools import DevToolsPlugin
from pydantic_ai import Agent
from pydantic_ai.messages import ModelMessage

"""
AI Chat — PydanticAI + Microsoft Teams SDK
==========================================
This sample shows how to build a streaming, memory-aware AI bot on Teams
using PydanticAI as the AI layer.

What it demonstrates:
  - Streaming:  token chunks from the model are piped live into a Teams
                conversation as they arrive.
  - Memory:     each conversation keeps its own history so the model can
                reference earlier messages in the same thread.
  - AI label:   responses are marked "Generated by AI" — a Teams UI affordance
                that signals AI-generated content to the reader.

The Teams integration (streaming, the AI label, activity routing) is handled
by the Teams SDK. PydanticAI is responsible only for the model call. Swapping
to a different model or provider requires changing one line — see _model below.
"""

load_dotenv(find_dotenv(usecwd=True))

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = App(plugins=[DevToolsPlugin()])

# ---------------------------------------------------------------------------
# AI agent
#
# PydanticAI's model string follows the pattern "<provider>:<model-name>".
# To switch providers, change this one line — nothing else in the file changes:
#
#   "anthropic:claude-3-5-sonnet-latest"   # requires ANTHROPIC_API_KEY
#   "google-gla:gemini-2.0-flash"          # requires GOOGLE_API_KEY
#   "groq:llama-3.3-70b-versatile"         # requires GROQ_API_KEY
#   "mistral:mistral-large-latest"         # requires MISTRAL_API_KEY
#
# See https://ai.pydantic.dev/models/ for the full list of supported providers.
# ---------------------------------------------------------------------------

_model = f"openai:{getenv('OPENAI_MODEL', 'gpt-4o')}"

agent = Agent(
    model=_model,
    system_prompt=(
        "You are a helpful assistant embedded in Microsoft Teams. "
        "Be concise and friendly. "
        "If you don't know something, say so."
    ),
)

# ---------------------------------------------------------------------------
# Per-conversation memory
#
# PydanticAI stores conversation history as a list of ModelMessage objects —
# one list per conversation. After each response, all_messages() returns the
# complete history (both the user turn and the assistant turn just added).
# Passing that list back as message_history= on the next run gives the model
# full context of the thread so far.
#
# This sample keeps histories in memory. For a production bot, replace this
# dict with a persistent store so history survives restarts. The API is the
# same: read a list[ModelMessage], pass it in, write it back.
# ---------------------------------------------------------------------------

_histories: dict[str, list[ModelMessage]] = {}

# ---------------------------------------------------------------------------
# Message handler
# ---------------------------------------------------------------------------


@app.on_message
async def on_message(ctx: ActivityContext[MessageActivity]) -> None:
    """Respond to Teams messages with a streamed, memory-aware AI reply."""
    text = ctx.activity.text.strip()

    # "clear" resets this conversation's history so the model starts fresh.
    if text.lower() == "clear":
        _histories.pop(ctx.activity.conversation.id, None)
        await ctx.reply("Conversation history cleared.")
        return

    if not text:
        return

    history = _histories.get(ctx.activity.conversation.id, [])

    # Show a status update while the model is warming up. Teams displays this
    # as a typing indicator that disappears once the first token arrives.
    ctx.stream.update("Thinking...")

    async with agent.run_stream(text, message_history=history) as result:
        async for chunk in result.stream_text(delta=True):
            # Forward each token chunk to Teams. The SDK batches these into
            # streaming HTTP requests and handles rate limiting automatically.
            ctx.stream.emit(chunk)

        # Mark the response as AI-generated. Emitting a MessageActivityInput
        # with no text but with the AI entity causes the SDK to attach the
        # "Generated by AI" label to the final assembled message.
        ctx.stream.emit(MessageActivityInput().add_ai_generated())

        # Save history so the next message in this conversation has context.
        _histories[ctx.activity.conversation.id] = result.all_messages()


if __name__ == "__main__":
    asyncio.run(app.start())
