[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "microsoft-teams-graph"
version = "1.0.0"
description = "The Graph package for a Microsoft Teams agent"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Microsoft", email = "teams@microsoft.com" }]
keywords = ["microsoft", "teams", "ai", "bot", "agents"]
requires-python = ">=3.12"
dependencies = [
    "azure-identity",
    "azure-core",
    "msgraph-sdk",
    "cryptography",
    "PyJWT[crypto]"
]

[project.urls]
Homepage = "https://github.com/microsoft/teams.py"
Repository = "https://github.com/microsoft/teams.py"
Issues = "https://github.com/microsoft/teams.py/issues"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]
