# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Build, Lint & Test"

on:
  pull_request:
    paths:
      - packages/**
      - examples/**
  push:
    branches: ["main"]
    paths:
      - packages/**
      - examples/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-lint-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: read
      checks: write
      pull-requests: write

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    env:
      NBGV_REQUIRED: "1"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '8.x'

      - name: Install nbgv
        run: dotnet tool install -g nbgv

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          enable-cache: true

      - name: Install Python and dependencies
        run: |
          uv python install ${{ matrix.python-version }}
          uv python list
          uv run --python ${{ matrix.python-version }} python --version
          uv sync --python ${{ matrix.python-version }} --frozen --all-packages --group dev

      - name: Lint (Ruff)
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: check

      - name: Format (Ruff)
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "format"

      - name: Type Check (PyRight)
        run: |
          source .venv/bin/activate  # Execute script in current shell to use virtual environment
          pyright

      - name: Run Tests
        run: |
          source .venv/bin/activate
          uv run poe test-cov-ci
